clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  handlebars:
    image: node
    commands:
      - npm install handlebars -g
      - make handlebars
      - git status
      - bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes handlebars template ' && exit 1 )"
    when:
      matrix:
        TESTS: handlebars

matrix:
  include:
    - TESTS: handlebars
