kind: pipeline
name: handlebars

steps:
  - name: handlebars
    image: node
    commands:
      - npm install handlebars -g
      - make handlebars
      - git status
      - bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes handlebars template ' && exit 1 )"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
